---
name: Test

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "nomad-actions"

      - name: Test actions locally
        uses: ./nomad-actions/
        with:
          addr: "https://nomad.nomad.nomad"

      - name: Test installed
        run: |
          nomad version
